# Generated by Django 3.0.3 on 2020-04-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.Authors'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
