# Generated by Django 3.0.3 on 2020-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20200418_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Notes Here'),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.Authors'),
        ),
    ]
